### ISSUE TITLE
Drafts for follow up sequence are "generated" but don't appear in my inbox

### ISSUE THREAD

**Issue by OShea-K** [azorin-studio/get-reply#16]
* See image below [1]
* Issue: Follow up sequence not working

To reproduce:
* Send email and bcc the sequence email address (testing-round2@getreply.app)
* Check logs: the sequence follow ups are "generated" on the getreply app.
* Monitor email inbox: no email is received (even after 15 min). Follow up intervals were set at 1 and 3 min. 

[1]
<img width="1624" alt="Screenshot 2023-06-14 at 23 25 35" src="https://github.com/azorin-studio/get-reply/assets/94146653/2fadc746-47ba-4997-b387-52539163fc5f">

**Comment by eoinmurray** [comment]
Thanks for reporting this, I've got it reproducing with some tests (intermittently which is weird) but I'll fix tomorrow and ping you.

Thanks for the help

**Comment by eoinmurray** [comment]
fixed async steps
