### ISSUE TITLE
The prompt page is generally not clear to me right now

### ISSUE THREAD

**Issue by OShea-K** [azorin-studio/get-reply#31]
I want to make my own prompt to ChatGPT. But what would be helpful here is an example prompt (e.g. the one used for the default sequences). Even though i've seen the default prompt before, I still feel a little lost on this page on how I should word the prompt / speak to the AI. So new users will definitely feel confused here. 

At the moment there is just an example Email Body text, which doesn't help me.

**Comment by eoinmurray** [comment]
I think for now I'm gonna turn off custom prompts, I want to focus on the core loop for now.
