### ISSUE TITLE
Not receiving expected follow up drafts

### ISSUE THREAD

**Issue by OShea-K** [azorin-studio/get-reply#32]
Log ID: da2865c6-0763-41bb-be48-d3ffbf14242b

* Created a sequence with multiple follow ups (now, 30 sec, 5 min, 1 hour, 1 day).
* I received multiple confirmation emails for the follow ups. 
* But I only received the draft email for the immediate follow up, not the 30 sec or 5 min (it's been 45 min, so nothing to do with email delays).

**Comment by eoinmurray** [comment]
Setting up longer tests with github ci
