### ISSUE TITLE
Only picking up on 1 stage of the sequence

### ISSUE THREAD

**Issue by OShea-K** [azorin-studio/get-reply#35]
Created 2 test sequences:

* https://getreply.app/logs/2241a087-b82f-4526-804a-bbaa37494bde
* https://getreply.app/logs/007b0e78-76ca-4f34-a808-68ce5a750fab

* Both sequences have 2 stages (5 min and 20 min / 3 min and 10 min).
* But - for both sequences - I only received the email confirmation and generated message for the second stage (10 min and 20 min).
* Even on the logs page, only one stage has been captured for some reason.

Feel free to log into my email to see - they should be at the top of the inbox.

**Comment by OShea-K** [comment]
In terms of user flow, I think it might be best to reject the email & respond with an error notification? The reason why is, if the earlier email is the one in which I make the mistake (1d), but getreply starts the sequence with the correct email (5d), then there's no way for me to "re-do" the email & trigger a reminder + chatgpt generated message for 1d. I'd have to manually snooze the 1d and create my message.

**Comment by eoinmurray** [comment]
Great points

**Comment by eoinmurray** [comment]
I think I've fixed this, so retest when you can

**Comment by OShea-K** [comment]
Tested. Seems like the issue has just swapped around. 
The first stage & reminder in the sequence is generated now but the subsequent stage never arrives. 
Email in your inbox.

**Comment by eoinmurray** [comment]
hmm...in future use me as the target for your emails AND make sure to use
cc and not bcc, so that I can verify the stages of the seqence

**Comment by OShea-K** [comment]
ok will do, but have you reproduced the bug?

**Comment by eoinmurray** [comment]
I have, I was only handling the cc case well, I had a design error in the
handling of bcc, fixing this soon.
