### ISSUE TITLE
Remove the Prompt link on the generated email until that page is ready

### ISSUE THREAD

**Issue by OShea-K** [azorin-studio/get-reply#36]
Remove the [Regenerate the message on using ChatGPT on GetReply] link in the reminded email until the page is ready. On that page there's no way for me to edit (or even understand) how the original message was generated. There's no options under 'Choose Prompt' and no real guidance for creating a new prompt.

Recommendation: remove link until you've built that page properly.

**Comment by eoinmurray** [comment]
totally agree

**Comment by eoinmurray** [comment]
fixed in 2aacc0f
